# lancement: docker compose up
version: '3.8'

services:
  # Service pour le bot discord (Node.js)
  bot:
    build:
      context: ./services/bot
    volumes:
      - ./services/bot:/app
    ports:
      # 80 (http) or 443 (https)
      - "80:80"
      - "443:443"

  # Service pour le site internet (Go)
  site:
    build:
      context: ./services/site
    volumes:
      - ./services/site:/app
    ports:
      - "8080:8080"

  # Service HHTPS (Externe)
  # caddy:
  #   image: caddy:2-alpine
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - bot
  #     - site
